Proper security statements in README
francoismichel/ssh3 pull request #59
Opened 2023-12-18 09:58 UTC by ei-grad

2023-12-18 13:19 UTC, francoismichel requested changes
Thank you so much for the PR !
I've made a few comments, let me know if you're okay with it, and if you're not, let's iterate on it.

2023-12-18 13:19 UTC, francoismichel commented on README.md
> +Given the current prototype state, we advise **testing SSH3 only on private networks**. Making experimental servers directly Internet-accessible could introduce risk before thorough security vetting.
What about rephrasing like this ?

> Given the current prototype state, we advise **testing SSH3 in sandboxed environments or private networks**. Be aware that making experimental servers directly Internet-accessible could introduce risk before thorough security vetting.

I want users to be aware of the risks of deploying public instances for sure and there may exist unknown issues with the current implem. However, I think it might be quite acceptable to deploy it on test/sandbox instances, using secret link if needed. It may be prematurate for production use, but I want to encourage people that know about security to test and experiment with us.

2023-12-18 13:19 UTC, francoismichel commented on README.md
> +## 🥷 Your SSH3 server should not yet be made public
what about ?

> ## 🥷 Do not deploy the SSH3 server on your production servers for now

It is a suggestion, it is okay if you want to refine it, let's iterate.

2023-12-18 13:19 UTC, francoismichel commented on README.md
> +## ⚡ SSH3 is an experimental prototype
I would change the lightning emoji to: 🧪 and rephrase like this if you're okay:

> ## 🧪 SSH3 is still experimental

2023-12-18 14:00 UTC, francoismichel commented
I would also like to refer Issue #57 in the README, by stating that if one has security questions, there is an open discussions with some answers there. Would you like to add that as well ?

2023-12-18 14:57 UTC, ei-grad commented
@francoismichel I agree, all your wording suggestions look better. I've committed these changes and credited you as the author. Shall we address the security questions in a separate pull request? I believe it would be worthwhile to add some information to the SECURITY.md file in the repository.

2023-12-18 15:17 UTC, francoismichel requested changes
Maybe a last thing:
When looking at the global readme, these large sections disturb a bit the flow of the README: we talk about SSH3 features, then we say that it is experimental, then we ask for support and then we discuss security and then new features again.

Most of the added sections concern security and could be put inside the `🔒 SSH3 security` section as subsections, so that when people have questions on security, they only have one section to look at. Doing so will also make the Security section appear earlier in the readme which is probably desirable.

So maybe let's re-organize it like that, if you're OK:

> ## 🔒 SSH3 security
> [current text of the security section]
> 
> ### 🧪 SSH3 is still experimental
> [the text you wrote]
> 
> ### 🥷 Do not deploy the SSH3 server on your production servers for now
> [the text you wrote]

And maybe move the `🙏 Community support` section between the `💐 SSH3 is already feature-rich` and the `Installing SSH3` section; like this:

> ## 💐 SSH3 is already feature-rich
> [current text of the feature section]
> 
> ## 🙏 Community support
> [the text you wrote]
> 
> ## Installing SSH3
> [...]
If you want, I can do the reorganization and let you cross-check, or you can do it if you prefer. :-)

And I think with that I am totally good! Thank you again !

2023-12-18 15:17 UTC, francoismichel commented on README.md
> +While [hidding](#-your-ssh3-public-server-can-be-hidden) servers behind secret paths has potential benefits, it
hidding->hiding

2023-12-18 15:17 UTC, francoismichel commented on README.md
> +## 🙏 Community support needed
I would just call it `🙏 Community support` which, to me, looks more like classical community-oriented repos

2023-12-19 10:59 UTC, b35363 approved these changes

2023-12-19 11:29 UTC, mpiraux reviewed
I like the tone of the new statements. I have a minor suggestion but I don't feel to strongly about it.

2023-12-19 11:29 UTC, mpiraux commented on README.md
> +public launch. We are excited by SSH3's future possibilities but
```suggestion
entering production. We are excited by SSH3's future possibilities but 
```
SSH3 is already public per se

2023-12-19 12:46 UTC, francoismichel commented on README.md
> +public launch. We are excited by SSH3's future possibilities but
I agree with the suggestion

2024-01-04 14:45 UTC, mpiraux commented
Can we proceed with the changes proposed in this PR and comments? I feel this would add to the README and as such is good to merge sometime soon :)

2024-01-04 21:43 UTC, ei-grad commented
Updated the code, please recheck if all proposed changes done right and the merge is correct.

2024-01-08 16:42 UTC, francoismichel approved these changes

2024-01-08 16:56 UTC, merged

2024-01-08 16:57 UTC, francoismichel commented
Rebased your branch with main and then merged in [9259245](https://github.com/francoismichel/ssh3/commit/9259245f2be4f6327054ec7fb78d41c84fa97788), thank you very much for the work !